// WADE (Web App Development Engine) 0.9.1 - Copyright Clockwork Chilli ltd 2012-2013 - all rights reserved 
function Animation(a,b,c,d,e,f,h){this._image=wade.getImage(a);this._imageName=a;this._numCells={x:b?b:1,y:c?c:1};this._startFrame=f?f:0;this._endFrame="undefined"!=typeof h?h:b*c-1;this._speed=d?d:0;this._looping=e;this._currentFrame=this._startFrame;this._playing=!1;this._time=0;this._direction=1;this._playMode="normal";this._frameFraction=0;this._stopped=!1;this._frameSize={x:this._image.width/this._numCells.x,y:this._image.height/this._numCells.y};this._updateFrameCenter()}
Animation.prototype.getImageSize=function(){return{x:this._image.width/this._numCells.x,y:this._image.height/this._numCells.y}};Animation.prototype.getImageName=function(){return this._imageName};
Animation.prototype.play=function(a){this._time=0;this._direction=a&&"reverse"==a?-1:1;this._playMode=a;a=this._currentFrame;this._currentFrame=1==this._direction?this._startFrame:this._endFrame;a!=this._currentFrame&&this._updateFrameCenter();a=this._playing;this._playing=!0;this._stopped=!1;if(this.sprite&&this.name)this.sprite.onAnimationStart(this.name,a)};Animation.prototype.stop=function(){this._playing=!1;this._stopped=!0};
Animation.prototype.resume=function(){this._playing||(this._stopped?(this._playing=!0,this._stopped=!1):this.play())};
Animation.prototype.step=function(){this._time+=wade.c_timeStep;var a=this._currentFrame,b=this._speed*this._time+wade.c_epsilon-0.5,c=Math.round(b);this._frameFraction=b-c+0.5;this._currentFrame=1==this._direction?c+this._startFrame:this._endFrame-c;if(a!=this._currentFrame){if(1==this._direction){if(this._currentFrame>this._endFrame)if("ping-pong"==this._playMode)this._currentFrame=this._endFrame,this._direction=-1,this._time=0;else if(this._looping)this._currentFrame=this._startFrame,this._time-=
(this._endFrame-this._startFrame+1)/this._speed;else if(this._currentFrame=this._endFrame,this._playing=!1,this._time=0,this.sprite&&this.name)this.sprite.onAnimationEnd(this.name)}else if(this._currentFrame<this._startFrame)if(this._looping)"ping-pong"==this._playMode?(this._currentFrame=this._startFrame,this._direction=1,this._time=0):(this._currentFrame=this._endFrame,this._time-=(this._endFrame-this._startFrame+1)/this._speed);else if(this._currentFrame=this._startFrame,this._playing=!1,this._time=
0,this.sprite&&this.name)this.sprite.onAnimationEnd(this.name);this._updateFrameCenter();this.sprite&&this.sprite.isVisible()&&this.sprite.setDirtyArea()}};Animation.prototype.isPlaying=function(){return this._playing};Animation.prototype.setBlending=function(a){"undefined"==typeof a&&(a=!0);this.draw=a?this._drawBlended:this._drawSingle};Animation.prototype.clone=function(){var a=new Animation;jQuery.extend(a,this);a.sprite=0;return a};
Animation.prototype._drawSingle=function(a,b,c){wade.numDrawCalls++;a.drawImage(this._image,this._frameCenter.x,this._frameCenter.y,this._frameSize.x,this._frameSize.y,b.x-c.x/2,b.y-c.y/2,c.x,c.y)};
Animation.prototype._drawBlended=function(a,b,c){var d=0<this._frameFraction?this._currentFrame+this._direction:this._currentFrame-this._direction;if(d<this._startFrame){if("ping-pong"==this._playMode||!this._looping){this._drawSingle(a,b,c);return}d=this._endFrame}else if(d>this._endFrame){if("ping-pong"==this._playMode||!this._looping){this._drawSingle(a,b,c);return}d=this._startFrame}var e=d%this._numCells.x*this._frameSize.x,d=Math.floor(d/this._numCells.x)*this._frameSize.y;wade.numDrawCalls+=
2;var f=a.globalAlpha;a.globalAlpha=f*(1-this._frameFraction);a.drawImage(this._image,this._frameCenter.x,this._frameCenter.y,this._frameSize.x,this._frameSize.y,b.x-c.x/2,b.y-c.y/2,c.x,c.y);a.globalAlpha=f*this._frameFraction;a.drawImage(this._image,e,d,this._frameSize.x,this._frameSize.y,b.x-c.x/2,b.y-c.y/2,c.x,c.y);a.globalAlpha=f;this.sprite&&this.sprite.isVisible()&&this.sprite.setDirtyArea()};Animation.prototype.draw=Animation.prototype._drawSingle;
Animation.prototype._updateFrameCenter=function(){this._frameCenter={x:this._currentFrame%this._numCells.x*this._frameSize.x,y:Math.floor(this._currentFrame/this._numCells.x)*this._frameSize.y}};
function AssetLoader(){this.loadingStatus=[];this.loadedImages=[];this.loadedAudio=[];this.loadedJson=[];this.attemptsCount=[];this.maxAttempts=5;this.loadingRequests={scripts:0,json:0,images:0,audio:0};this.loadingSuccess={scripts:0,json:0,images:0,audio:0};this.loadingErrors={scripts:0,json:0,images:0,audio:0};this.init=function(){var a=!1;try{window.AudioContext=window.AudioContext||window.webkitAudioContext,this.audioContext=new AudioContext,a=XMLHttpRequest&&"string"===typeof(new XMLHttpRequest).responseType}catch(b){}a||
console.log("Warning: the WebAudio API is not supported by this browser. Audio functionality will be limited");(a=new Audio)?this.audioExtension=a.canPlayType("audio/ogg; codecs=vorbis")?"ogg":"aac":console.log("Warning: Unable to initialise audio.")};this.updateAttempts=function(a,b){this.attemptsCount[a]?this.attemptsCount[a]++:(this.attemptsCount[a]=1,this.loadingRequests[b]++)};this.loadScript=function(a,b,c,d){if("ok"==this.loadingStatus[a]||"loading"==this.loadingStatus[a]){if(!c){"ok"==this.loadingStatus[a]&&
b&&b();return}this.attemptsCount[a]=0}this.loadingStatus[a]="loading";this.updateAttempts(a,"scripts");$.ajax({cache:c?!1:!0,type:"GET",url:a,dataType:"script",timeout:15E3,success:this.scriptLoaded(a,b),error:this.scriptLoadingError(a,b,c,d)})};this.loadJson=function(a,b,c,d,e){if("ok"==this.loadingStatus[a]||"loading"==this.loadingStatus[a]){if(!d){"ok"==this.loadingStatus[a]&&(b&&(b.data=this.loadedJson[a]),c&&c());return}this.attemptsCount[a]=0}this.loadingStatus[a]="loading";this.updateAttempts(a,
"json");$.ajax({cache:d?!1:!0,type:"GET",url:a,dataType:"json",timeout:15E3,success:this.jsonLoaded(a,b,c),error:this.jsonLoadingError(a,b,c,d,e)})};this.loadAppScript=function(a,b){this.updateAttempts(a,"scripts");$.ajax({cache:b?!1:!0,type:"GET",url:a,dataType:"script",timeout:15E3,success:this.appLoaded(a),error:this.appLoadingError(a)})};this.loadImage=function(a,b,c){if("ok"==this.loadingStatus[a])b&&b();else if("loading"==this.loadingStatus[a])this.loadedImages[a]&&this.loadedImages[a].callbackIsSet&&
b&&console.log("Warning: conflicting callbacks for the load event of image "+a);else{this.loadingStatus[a]="loading";this.updateAttempts(a,"images");var d=new Image;this.loadedImages[a]=d;d.addEventListener("load",this.imageLoaded(a,b),!1);d.addEventListener("error",this.imageLoadingError(a,b,c),!1);d.callbackIsSet=b?1:0;d.src=a}};this.unloadImage=function(a){if("ok"!=this.loadingStatus[a])return!1;this.loadedImages[a]=null;this.loadingStatus[a]="";this.attemptsCount[a]=0;return!0};this.unloadAllImages=
function(){for(var a in this.loadedImages)this.loadedImages.hasOwnProperty(a)&&this.unloadImage(a)};this.imageLoaded=function(a,b){var c=this;return function(){c.loadingSuccess.images++;c.loadingStatus[a]="ok";window.wade&&wade.setImage(a,c.loadedImages[a]);c.handleLoadingCallback(b)}};this.imageLoadingError=function(a,b,c){var d=this;return function(){d.loadingErrors.images++;d.loadingStatus[a]="error";d.attemptsCount[a]<d.maxAttempts?c?c():console.log("Unable to load image "+a):d.loadImage(a,b,
c)}};this.setImage=function(a,b){(this.loadedImages[a]=b)&&(this.loadingStatus[a]="ok")};this.setAudio=function(a,b){(this.loadedAudio[a]=b)&&(this.loadingStatus[a]="ok")};this.jsonLoaded=function(a,b,c){var d=this;return function(e){d.loadingSuccess.json++;d.loadingStatus[a]="ok";d.loadedJson[a]=e;b&&(b.data=e);d.handleLoadingCallback(c)}};this.scriptLoaded=function(a,b){var c=this;return function(){c.loadingSuccess.scripts++;c.loadingStatus[a]="ok";c.handleLoadingCallback(b)}};this.scriptLoadingError=
function(a,b,c,d){var e=this;return function(){e.loadingErrors.scripts++;e.loadingStatus[a]="error";e.attemptsCount[a]<e.maxAttempts?d?d():console.log("Unable to load script "+a):e.loadScript(a,b,c,d)}};this.jsonLoadingError=function(a,b,c,d,e){var f=this;return function(){f.loadingErrors.json++;f.loadingStatus[a]="error";f.attemptsCount[a]<f.maxAttempts?e?e():console.log("Unable to load json file "+a):f.loadJson(a,b,c,d,e)}};this.appLoaded=function(a){var b=this;return function(){b.loadingSuccess.scripts++;
b.loadingStatus[a]="ok";wade.instanceApp()}};this.appLoadingError=function(a){var b=this;return function(){b.loadingErrors.scripts++;b.loadingStatus[a]="error";b.attemptsCount[a]<b.maxAttempts?alert("Unable to load main app script "+a):b.loadAppScript(a)}};this.loadAudio=function(a,b,c,d,e){this.updateAttempts(a,"audio");var f=a.substr(a.length-3).toLowerCase(),h=a;if(f!=this.audioExtension&&("aac"==f||"ogg"==f))h=a.substr(0,a.length-3)+this.audioExtension;if(this.audioContext){var l=this,j=new XMLHttpRequest;
j.open("GET",h,!0);j.responseType="arraybuffer";j.timeout=6E4;j.onload=function(){l.audioContext.decodeAudioData(j.response,function(f){l.loadedAudio[a]=f;l.audioLoaded(a,d)();b&&wade.playAudio(a,c)},l.audioLoadingError(a,b,c,d,e))};j.send()}else f=new Audio,f.autoplay=b,f.loop=c,f.name=a,f.addEventListener("canplaythrough",this.audioLoaded(a,d),!1),f.addEventListener("error",this.audioLoadingError(a,b,c,d,e),!1),c&&f.addEventListener("ended",function(){this.currentTime=0;this.play()},!1),f.src=h,
f.load(),this.loadedAudio[a]=f};this.unloadAudio=function(a){if("ok"!=this.loadingStatus[a])return!1;this.loadedAudio[a]=null;this.loadingStatus[a]="";this.attemptsCount[a]=0;return!0};this.unloadAllAudio=function(){for(var a in this.loadedAudio)this.loadedAudio.hasOwnProperty(a)&&this.unloadAudio(a)};this.audioLoaded=function(a,b){var c=this;return function(){"ok"!=c.loadingStatus[a]&&(c.loadingSuccess.audio++,window.wade&&wade.setAudio(a,c.loadedAudio[a]),c.loadingStatus[a]="ok",c.handleLoadingCallback(b))}};
this.audioLoadingError=function(a,b,c,d,e){var f=this;return function(){f.loadingErrors.audio++;f.loadingStatus[a]="error";f.attemptsCount[a]<f.maxAttempts?e?e():console.log("Unable to load audio "+a):f.loadAudio(a,b,c,d,e)}};this.isFinishedLoading=function(){return this.loadingRequests.scripts==this.loadingSuccess.scripts&&this.loadingRequests.json==this.loadingSuccess.json&&this.loadingRequests.images==this.loadingSuccess.images&&this.loadingRequests.audio==this.loadingSuccess.audio};this.getPercentageComplete=
function(){return 100*(this.loadingSuccess.scripts+this.loadingSuccess.json+this.loadingSuccess.images+this.loadingSuccess.audio)/(this.loadingRequests.scripts+this.loadingRequests.json+this.loadingRequests.images+this.loadingRequests.audio)};this.getImage=function(a){if("ok"==this.loadingStatus[a])return this.loadedImages[a];console.log("Warning: Trying to get image "+a+" without loading it first");return wade.getImage()};this.getAudio=function(a){if("ok"==this.loadingStatus[a])return this.loadedAudio[a];
console.log("Warning: Trying to get audio "+a+" without loading it first");return new Audio};this.getLoadingStatus=function(a){return(a=this.loadingStatus[a])?a:"unknown"};this.setGlobalCallback=function(a){a&&this.isFinishedLoading()?(a(),this.globalCallback=0):this.globalCallback=a};this.handleLoadingCallback=function(a){a&&a();this.globalCallback&&this.isFinishedLoading()&&(this.globalCallback(),this.setGlobalCallback(0))};this.getWebAudioContext=function(){return this.audioContext}}
function InputManager(){var a=this,b=!1,c=0,d,e=[],f=[],h=[],l=[],j=0,i=5,g={},k=function(a,b){"string"==typeof b&&(b=document.getElementById(b));if(null!=b){var c;c=(c=a)?c:window.event;c=isNaN(window.scrollX)?{x:document.documentElement.scrollLeft+document.body.scrollLeft+c.clientX,y:document.documentElement.scrollTop+document.body.scrollTop+c.clientY}:{x:window.scrollX+c.clientX,y:window.scrollY+c.clientY};c.x-=b.offsetLeft+b.clientLeft+b.clientWidth/2;c.y-=b.offsetTop+b.clientTop+b.clientHeight/
2;c.x*=b.width/b.clientWidth;c.y*=b.height/b.clientHeight;if(wade.isScreenRotated()){var d=c.y;c.y=-c.x;c.x=d}return c}},m=function(a){a=a?a:window.event;a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();a.returnValue=!1;a.cancel=!0;a.cancelBubble=!0};this.init=function(){window.addEventListener("mousedown",this.event_mouseDown);window.addEventListener("mouseup",this.event_mouseUp);window.addEventListener("mousemove",this.event_mouseMove);window.addEventListener("mousewheel",
this.event_mouseWheel);window.addEventListener("DOMMouseScroll",this.event_mouseWheel);window.addEventListener("touchstart",this.event_touchStart);window.addEventListener("touchend",this.event_touchEnd);window.addEventListener("touchmove",this.event_touchMove);window.addEventListener("keydown",this.event_keyDown);window.addEventListener("keyup",this.event_keyUp);window.addEventListener("keypress",this.event_keyPress);navigator.msPointerEnabled&&(window.addEventListener("MSPointerDown",this.event_pointerDown),
window.addEventListener("MSPointerMove",this.event_pointerMove),window.addEventListener("MSPointerUp",this.event_pointerUp))};this.deinit=function(){window.removeEventListener("mousedown",this.event_mouseDown);window.removeEventListener("mouseup",this.event_mouseUp);window.removeEventListener("mousemove",this.event_mouseMove);window.removeEventListener("mousewheel",this.event_mouseWheel);window.removeEventListener("DOMMouseScroll",this.event_mouseWheel);window.removeEventListener("touchstart",this.event_touchStart);
window.removeEventListener("touchend",this.event_touchEnd);window.removeEventListener("touchmove",this.event_touchMove);window.removeEventListener("keydown",this.event_keyDown);window.removeEventListener("keyup",this.event_keyUp);window.removeEventListener("keypress",this.event_keyPress);navigator.msPointerEnabled&&(window.removeEventListener("MSPointerDown",this.event_pointerDown),window.removeEventListener("MSPointerMove",this.event_pointerMove),window.removeEventListener("MSPointerUp",this.event_pointerUp))};
this.event_mouseDown=function(c){var n={screenPosition:k(c,"canvas")};a._setLastMousePosition(n.screenPosition.x,n.screenPosition.y);var r=(new Date).getTime();if(f.mouseDown&&e.mouseDown&&r-e.mouseDown<f.mouseDown||f.mouseUp&&e.mouseUp&&r-e.mouseUp<f.mouseUp)return!1;if(!b){j={x:n.screenPosition.x,y:n.screenPosition.y};n.button=c.button;d=c;if(!wade.processEvent("onMouseDown",n)&&wade.app&&wade.app.onMouseDown)wade.app.onMouseDown(n);m(c);b=!0;e.mouseDown=r}return!1};this.event_mouseUp=function(c){var n=
{screenPosition:k(c,"canvas")};a._setLastMousePosition(n.screenPosition.x,n.screenPosition.y);var r=(new Date).getTime();if(f.mouseUp&&e.mouseUp&&r-e.mouseUp<f.mouseUp)return!1;if(b){b=!1;n.button=c.button;d=c;var h=n.screenPosition.x-j.x,q=n.screenPosition.y-j.y;j=0;h*h+q*q<=i*i&&a.event_click(n);if(!wade.processEvent("onMouseUp",n)&&wade.app&&wade.app.onMouseUp)wade.app.onMouseUp(n);!e.mouseUp&&(navigator&&navigator.userAgent.match(/(iPod|iPhone|iPad)/)&&navigator.userAgent.match(/AppleWebKit/))&&
wade.playSilentSound();m(c);e.mouseUp=r}return!1};this.event_mouseMove=function(b){var c={screenPosition:k(b,"canvas")};a._setLastMousePosition(c.screenPosition.x,c.screenPosition.y);var r=(new Date).getTime();if(!f.mouseMove||!(e.mouseMove&&r-e.mouseMove<f.mouseMove)){d=b;if(!wade.processEvent("onMouseMove",c)&&wade.app&&wade.app.onMouseMove)wade.app.onMouseMove(c);e.mouseMove=r;m(b)}};this.event_mouseWheel=function(b){var b=b?b:window.event,c={screenPosition:k(b,"canvas")};a._setLastMousePosition(c.screenPosition.x,
c.screenPosition.y);var r=(new Date).getTime();if(!f.mouseWheel||!(e.mouseWheel&&r-e.mouseWheel<f.mouseWheel)){c.value=b.detail?-1*b.detail:b.wheelDelta/40;d=c;if(!wade.processEvent("onMouseWheel",c)&&wade.app&&wade.app.onMouseWheel)wade.app.onMouseWheel(c);e.mouseWheel=r;m(b)}};this.event_click=function(a){var b=(new Date).getTime();if(!f.onClick||!(e.onClick&&b-e.onClick<f.onClick)){if(!wade.processEvent("onClick",a)&&wade.app&&wade.app.onClick)wade.app.onClick(a);e.onClick=b}};this.event_touchStart=
function(b){var d=b.touches||l;if(2==d.length){var f=d[0].pageX-d[1].pageX,d=d[0].pageY-d[1].pageY;c=Math.sqrt(f*f+d*d)}else 1==d.length&&a.event_mouseDown(d[0]);m(b)};this.event_touchEnd=function(b){a.event_mouseUp(d);m(b)};this.event_touchMove=function(b){var d=b.touches||l;if(2==d.length){var f=d[0].pageX-d[1].pageX,e=d[0].pageY-d[1].pageY;if(f=Math.sqrt(f*f+e*e))e=c-f,Math.abs(e)>wade.c_epsilon&&(e=-30*e/Math.max(wade.getScreenWidth(),wade.getScreenHeight()),a.event_mouseWheel({clientX:d[0].pageX,
clientY:d[0].pageY,detail:-e}));c=f}else 1==d.length&&a.event_mouseMove({clientX:d[0].pageX,clientY:d[0].pageY});m(b)};this.event_keyDown=function(a){var b={keyCode:"which"in a?a.which:a.keyCode,shift:a.shiftKey,ctrl:a.ctrlKey,alt:a.altKey,meta:a.metaKey};wade.processEvent("onKeyDown",b)?m(a):wade.app&&(wade.app.onKeyDown&&wade.app.onKeyDown(b))&&m(a)};this.event_keyUp=function(a){var b={keyCode:"which"in a?a.which:a.keyCode,shift:a.shiftKey,ctrl:a.ctrlKey,alt:a.altKey,meta:a.metaKey};wade.processEvent("onKeyUp",
b)?m(a):wade.app&&(wade.app.onKeyUp&&wade.app.onKeyUp(b))&&m(a)};this.event_keyPress=function(a){var b={charCode:"charCode"in a?a.charCode:a.keyCode};wade.processEvent("onKeyPress",b)?m(a):wade.app&&(wade.app.onKeyPress&&wade.app.onKeyPress(b))&&m(a)};this.event_pointerDown=function(b){h[b.pointerId]||(h[b.pointerId]=1,l.push({pageX:b.pageX,pageY:b.pageY,clientX:b.clientX,clientY:b.clientY,pointerId:b.pointerId}),a.event_touchStart(b))};this.event_pointerUp=function(b){if(h[b.pointerId]){for(var c=
0;c<l.length;c++)if(l[c].pointerId==b.pointerId){wade.removeObjectFromArrayByIndex(c,l);break}h[b.pointerId]=0;a.event_touchEnd(b)}};this.event_pointerMove=function(b){if(h[b.pointerId]){for(var c=0;c<l.length;c++)if(l[c].pointerId==b.pointerId){l[c].pageX=b.pageX;l[c].pageY=b.pageY;l[c].clientX=b.clientX;l[c].clientY=b.clientY;break}a.event_touchMove(b)}};this.isMouseDown=function(){return b};this.setMinimumIntervalBetweenEvents=function(a,b){f[a]=b};this.setClickTolerance=function(a){i=a};this.getMousePosition=
function(){return{x:g.x,y:g.y}};this._setLastMousePosition=function(a,b){if(a!=g.x||b!=g.y)wade.updateMouseInOut(g,{x:a,y:b}),g.x=a,g.y=b}}
function Layer(a){this.id=a;this._sprites=[];this._movingSprites=[];this._transform={scale:1,translate:1};this._sorting="none";this._dirtyAreas=[];this._smoothing=this._clearCanvas=this._needsFullRedraw=!0;this._resolutionFactor=wade.getResolutionFactor();this._cameraPosition=wade.getCameraPosition();this._updateScaleConversionFactor();this._canvas=wade.createCanvas(this._resolutionFactor);this._canvas.style.zIndex=-a;this._context=this._canvas.getContext("2d");this._context.save();wade.isDoubleBufferingEnabled()&&
this.createSecondaryCanvas();var a=wade.getScreenWidth()/2,b=wade.getScreenHeight()/2;this._worldBounds={minX:-a,minY:-b,maxX:a,maxY:b};this._initQuadTree();this._isAndroidStockBrowser=0<=navigator.userAgent.indexOf("Android")&&-1==navigator.userAgent.indexOf("Firefox")&&!(window.chrome&&window.chrome.app)}Layer.prototype.getScaleFactor=function(){return this._transform.scale};Layer.prototype.getTranslateFactor=function(){return this._transform.translate};
Layer.prototype.setTransform=function(a,b){this._transform.scale=a;this._transform.translate=b;this._updateScaleConversionFactor();this._needsFullRedraw=!0};Layer.prototype.getSorting=function(){return this._sorting};
Layer.prototype.setSorting=function(a){if(a!=this._sorting){this._sorting=a;switch(a){case "bottomToTop":this._sortingFunction=this._spriteSorter_bottomToTop;break;case "topToBottom":this._sortingFunction=this._spriteSorter_topToBottom;break;case "none":this._sortingFunction=0;break;default:this._sortingFunction=a}this._needsFullSorting=!0}};Layer.prototype.clearDirtyAreas=function(){this._dirtyAreas.length=0;this._needsFullRedraw=!1};Layer.prototype.addDirtyArea=function(a){this._dirtyAreas.push(a)};
Layer.prototype.addSprite=function(a){this._sprites.push(a);a.id=this._sprites.length;this.addDirtyArea(a.boundingBox);wade.expandBox(this._worldBounds,a.boundingBox);this._addSpriteToQuadTree(a);this._movingSprites.push(a)};Layer.prototype.removeSprite=function(a){this.addDirtyArea(a.boundingBox);wade.removeObjectFromArray(a,this._sprites);a.quadTreeNode.removeObject(a);a.quadTreeNode=0};
Layer.prototype.draw=function(){var a,b,c;if(0!=this._dirtyAreas.length||this._needsFullRedraw){this._isAndroidStockBrowser&&this._clearCanvas&&(this._needsFullRedraw=!0);var d=this._needsFullRedraw&&wade.isDoubleBufferingEnabled(),e=d?this._secondaryContext:this._context;this._needsFlipping=d;var f=wade.getScreenWidth()*this._resolutionFactor,h=wade.getScreenHeight()*this._resolutionFactor,d=f/2,l=h/2;if("none"!=this._sorting)if(this._needsFullSorting=this._needsFullSorting||this._movingSprites.length*
this._movingSprites.length>this._sprites.length)this._sprites.sort(this._sortingFunction);else for(a=0;a<this._movingSprites.length;a++){var j=0,i=this._movingSprites[a];for(b=0;b<this._sprites.length&&i!=this._sprites[b];b++);if(b<this._sprites.length){for(c=b+1;c<this._sprites.length;c++)if(0<this._sortingFunction(i,this._sprites[c]))this._sprites[c].setDirtyArea(),this._sprites[c-1]=this._sprites[c],this._sprites[c]=i,j++;else break;if(!j)for(c=b-1;0<=c;c--)if(0>this._sortingFunction(i,this._sprites[c]))this._sprites[c].setDirtyArea(),
this._sprites[c+1]=this._sprites[c],this._sprites[c]=i,j++;else break}}this._needsFullSorting=!1;this._movingSprites.length=0;a=this.screenBoxToWorld({minX:-d,minY:-l,maxX:d,maxY:l});this._needsFullRedraw?(e.restore(),e.save(),b=this._scaleConversionFactor,c=l-this._cameraPosition.y*this._transform.translate*b,e.setTransform(b,0,0,b,Math.round(d-this._cameraPosition.x*this._transform.translate*b),Math.round(c)),j=wade.cloneObject(a)):j=this._joinDirtyAreas();if(j){for(c=0;c<this._sprites.length;c++)this._sprites[c].needsDrawing=
0;for(c=0;c.minX!=j.minX||c.minY!=j.minY||c.maxX!=j.maxX||c.maxY!=j.maxY;){this._quadTree.flagObjects(j,"needsDrawing");c=wade.cloneObject(j);for(b=0;b<this._sprites.length;b++)this._sprites[b].needsDrawing&&this._sprites[b].isVisible()&&wade.expandBox(j,this._sprites[b].boundingBox);wade.clampBoxToBox(j,a)}this._clearCanvas&&(e.save(),e.setTransform(1,0,0,1,0,0),this._needsFullRedraw?e.clearRect(0,0,Math.round(f),Math.round(h)):(f=this.worldBoxToScreen(j),e.clearRect(Math.floor(f.minX+d-1),Math.floor(f.minY+
l),Math.ceil(f.maxX-f.minX+2),Math.ceil(f.maxY-f.minY+2))),e.restore());this.clearDirtyAreas();for(a=0;a<this._sprites.length;a++)this._sprites[a].needsDrawing&&this._sprites[a].draw(e)}else this.clearDirtyAreas(),this._movingSprites.length=0}};
Layer.prototype.onCameraPositionChanged=function(a){if(0!=this._transform.translate&&(a.x!=this._cameraPosition.x||a.y!=this._cameraPosition.y)||0!=this._transform.scale&&a.z!=this._cameraPosition.z)this._needsFullRedraw=!0;this._cameraPosition={x:a.x,y:a.y,z:a.z};this._updateScaleConversionFactor()};Layer.prototype.onSpritePositionChanged=function(a){wade.expandBox(this._worldBounds,a.boundingBox);a.quadTreeNode&&(a.quadTreeNode.removeObject(a),this._addSpriteToQuadTree(a));this._movingSprites.push(a)};
Layer.prototype.worldPositionToScreen=function(a){return{x:this._scaleConversionFactor*(a.x-this._cameraPosition.x*this._transform.translate),y:this._scaleConversionFactor*(a.y-this._cameraPosition.y*this._transform.translate)}};Layer.prototype.worldDirectionToScreen=function(a){return{x:this._scaleConversionFactor*a.x,y:this._scaleConversionFactor*a.y}};
Layer.prototype.worldBoxToScreen=function(a){var b={x:(a.maxX-a.minX)/2,y:(a.maxY-a.minY)/2},a=this.worldPositionToScreen({x:a.minX+b.x,y:a.minY+b.y}),b=this.worldDirectionToScreen(b);return{minX:a.x-b.x,minY:a.y-b.y,maxX:a.x+b.x,maxY:a.y+b.y}};Layer.prototype.screenPositionToWorld=function(a){return{x:this._cameraPosition.x*this._transform.translate+a.x/this._scaleConversionFactor,y:this._cameraPosition.y*this._transform.translate+a.y/this._scaleConversionFactor}};
Layer.prototype.screenDirectionToWorld=function(a){return{x:a.x/this._scaleConversionFactor,y:a.y/this._scaleConversionFactor}};Layer.prototype.screenBoxToWorld=function(a){var b={x:(a.maxX-a.minX)/2,y:(a.maxY-a.minY)/2},a=this.screenPositionToWorld({x:a.minX+b.x,y:a.minY+b.y}),b=this.screenDirectionToWorld(b);return{minX:a.x-b.x,minY:a.y-b.y,maxX:a.x+b.x,maxY:a.y+b.y}};
Layer.prototype.resize=function(a,b){this._canvas.width=Math.round(a*this._resolutionFactor);this._canvas.height=Math.round(b*this._resolutionFactor);this._secondaryCanvas&&(this._secondaryCanvas.width=Math.round(a*this._resolutionFactor),this._secondaryCanvas.height=Math.round(b*this._resolutionFactor));this._needsFullRedraw=!0;this._smoothing||(this._smoothing=!0,this.setSmoothing(!1))};Layer.prototype.setCanvasClearing=function(a){this._clearCanvas=a};Layer.prototype.getContext=function(){return this._context};
Layer.prototype.bringSpriteToFront=function(a){a.setDirtyArea();wade.removeObjectFromArray(a,this._sprites);this._sprites.push(a)};Layer.prototype.pushSpriteToBack=function(a){a.setDirtyArea();wade.removeObjectFromArray(a,this._sprites);this._sprites.splice(0,0,a)};
Layer.prototype.flipIfNeeded=function(){if(this._needsFlipping){var a=this._canvas,b=this._context;this._canvas=this._secondaryCanvas;this._context=this._secondaryContext;this._secondaryCanvas=a;this._secondaryContext=b;this._canvas.style.display="inline";this._secondaryCanvas.style.display="none";this._needsFlipping=!1}};
Layer.prototype.setCanvasStyleSize=function(a,b){if(a!=this._canvas.style.width||b!=this._canvas.style.height)this._canvas.style.width=a,this._canvas.style.height=b,this._secondaryCanvas&&(this._secondaryCanvas.style.width=a,this._secondaryCanvas.style.height=b)};
Layer.prototype.setCanvasStyleRotation=function(a){a=a?"rotate("+a+"deg)":"translate3d(0, 0, 0)";this._canvas.style.MozTransform=a;this._canvas.style.msTransform=a;this._canvas.style.OTransform=a;this._canvas.style.webkitTransform=a;this._canvas.style.transform=a;this._secondaryCanvas&&(this._secondaryCanvas.style.MozTransform=a,this._secondaryCanvas.style.msTransform=a,this._secondaryCanvas.style.OTransform=a,this._secondaryCanvas.style.webkitTransform=a,this._secondaryCanvas.style.transform=a)};
Layer.prototype.compareSprites=function(a,b){return this._sortingFunction?this._sortingFunction(a,b):a.id-b.id};Layer.prototype.removeCanvases=function(){document.body.removeChild(this._canvas);this.removeSecondaryCanvas()};Layer.prototype._updateScaleConversionFactor=function(){var a=wade.getCameraPosition();this._scaleConversionFactor=(this._transform.scale/a.z+1-this._transform.scale)*this._resolutionFactor};
Layer.prototype._spriteSorter_bottomToTop=function(a,b){var c=a.getPosition().y+a.getSortPoint().y*a.getSize().y-b.getPosition().y-b.getSortPoint().y*b.getSize().y;return Math.abs(c)<wade.c_epsilon?a.id-b.id:c};Layer.prototype._spriteSorter_topToBottom=function(a,b){var c=b.getPosition().y+b.getSortPoint().y*b.getSize().y-a.getPosition().y-a.getSortPoint().y*a.getSize().y;return Math.abs(c)<wade.c_epsilon?a.id-b.id:c};
Layer.prototype._initQuadTree=function(){var a=(this._worldBounds.maxX-this._worldBounds.minX)/2,b=(this._worldBounds.maxY-this._worldBounds.minY)/2,c=this._worldBounds.minX+a,d=this._worldBounds.minY+b;this._quadTree=new QuadTreeNode(0,c-1.5*a,d-1.5*b,c+1.5*a,d+1.5*b)};Layer.prototype._addSpriteToQuadTree=function(a){if(wade.boxContainsBox(this._quadTree,this._worldBounds))this._quadTree.addObject(a);else{this._initQuadTree();for(a=0;a<this._sprites.length;a++)this._quadTree.addObject(this._sprites[a])}};
Layer.prototype._joinDirtyAreas=function(){if(!this._dirtyAreas.length)return{minX:0,minY:0,maxX:0,maxY:0};for(var a=wade.getScreenWidth()/2,b=wade.getScreenHeight()/2,a=this.screenBoxToWorld({minX:-a,minY:-b,maxX:a,maxY:b}),b={minX:a.maxX,minY:a.maxY,maxX:a.minX,maxY:a.minY},c=0;c<this._dirtyAreas.length;c++){var d=this._dirtyAreas[c];wade.boxIntersectsBox(a,d)&&wade.expandBox(b,d)}wade.clampBoxToBox(b,a);if(b.maxX<=b.minX||b.maxY<=b.minY)b=0;return b};
Layer.prototype.createSecondaryCanvas=function(){this._secondaryCanvas=wade.createCanvas(this._resolutionFactor);this._secondaryCanvas.style.zIndex=-this.id;this._secondaryCanvas.style.display="none";this._secondaryContext=this._secondaryCanvas.getContext("2d");this._secondaryContext.imageSmoothingEnabled=this._secondaryContext.mozImageSmoothingEnabled=this._secondaryContext.mozImageSmoothingEnabled=this._secondaryContext.oImageSmoothingEnabled=this._secondaryContext.webkitImageSmoothingEnabled=this._smoothing;
this._secondaryContext.save()};Layer.prototype.removeSecondaryCanvas=function(){this._secondaryCanvas&&document.body.removeChild(this._secondaryCanvas);this._secondaryCanvas=null};Layer.prototype.setResolutionFactor=function(a){a!=this._resolutionFactor&&(this._resolutionFactor=a,this._updateScaleConversionFactor(),this.resize(wade.getScreenWidth(),wade.getScreenHeight()))};Layer.prototype.getResolutionFactor=function(){return this._resolutionFactor};
Layer.prototype.setSmoothing=function(a){a!=this._smoothing&&(this._smoothing=a,this._context.restore(),this._context.imageSmoothingEnabled=this._context.mozImageSmoothingEnabled=this._context.mozImageSmoothingEnabled=this._context.oImageSmoothingEnabled=this._context.webkitImageSmoothingEnabled=a,this._context.save(),this._secondaryContext&&(this._secondaryContext.restore(),this._secondaryContext.imageSmoothingEnabled=this._secondaryContext.mozImageSmoothingEnabled=this._secondaryContext.mozImageSmoothingEnabled=
this._secondaryContext.oImageSmoothingEnabled=this._secondaryContext.webkitImageSmoothingEnabled=a,this._secondaryContext.save()))};Layer.prototype.getSmoothing=function(){return this._smoothing};function QuadTreeNode(a,b,c,d,e){this._level=a;this.minX=b;this.minY=c;this.maxX=d;this.maxY=e;this._children=[];this._objects=[]}QuadTreeNode.prototype.c_idealObjectCountPerLevel=1;QuadTreeNode.prototype.c_maxLevels=8;
QuadTreeNode.prototype.addObject=function(a){if(!this._insertInChild(a)&&(a.quadTreeNode=this,this._objects.push(a),this._objects.length>this.c_idealObjectCountPerLevel&&!this._children.length&&this._level<this.c_maxLevels)){var a=this.minX+(this.maxX-this.minX)/2,b=this.minY+(this.maxY-this.minY)/2;this._children.push(new QuadTreeNode(this._level+1,this.minX,this.minY,a,b));this._children.push(new QuadTreeNode(this._level+1,a,this.minY,this.maxX,b));this._children.push(new QuadTreeNode(this._level+
1,this.minX,b,a,this.maxY));this._children.push(new QuadTreeNode(this._level+1,a,b,this.maxX,this.maxY));for(a=this._objects.length-1;0<=a;a--)this._insertInChild(this._objects[a])&&this.removeObject(this._objects[a])}};QuadTreeNode.prototype.removeObject=function(a){wade.removeObjectFromArray(a,this._objects)};
QuadTreeNode.prototype.getObjects=function(a){if(wade.boxIntersectsBox(this,a)){for(var b=[].concat(this._objects),c=0;c<this._children.length;c++)b=b.concat(this._children[c].getObjects(a));return b}return[]};QuadTreeNode.prototype.countObjects=function(a){if(wade.boxIntersectsBox(this,a)){for(var b=this._objects.length,c=0;c<this._children.length;c++)b+=this._children[c].countObjects(a);return b}return 0};
QuadTreeNode.prototype.flagObjects=function(a,b){if(wade.boxIntersectsBox(this,a)){for(var c=0;c<this._objects.length;c++)wade.boxIntersectsBox(a,this._objects[c].boundingBox)&&(this._objects[c][b]=1);for(c=0;c<this._children.length;c++)this._children[c].flagObjects(a,b)}};QuadTreeNode.prototype.empty=function(){for(var a=this._objects.length=0;a<this._children.length;a++)this._children[a].empty()};
QuadTreeNode.prototype._insertInChild=function(a){for(var b=0;b<this._children.length;b++)if(wade.boxContainsBox(this._children[b],a.boundingBox))return this._children[b].addObject(a),!0;return!1};
function Renderer(){var a=[],b=[],c=0,d=0,e=0,f="full",h=1920,l=1080,j=0,i=0,g=0,k=0,m=1,p=!0,n=!1;navigator&&navigator.userAgent&&navigator.userAgent.match(/MSIE/);this._createLayerIfNeeded=function(c){a[c]||(a[c]=new Layer(c),p||a[c].setSmoothing(p),b.push(a[c]),b.sort(this._layerSorter))};this.init=function(a){e=a;c=parseInt($("#canvas").attr("width"));d=parseInt($("#canvas").attr("height"))};this.draw=function(){var a,g;if(e.getSimulationDirtyState()){wade.numDrawCalls=0;var q=wade.logDrawTime&&
console.time&&console.timeEnd&&0.02>Math.random();q&&console.time("Draw");var s=document.getElementById("canvas"),u=wade.getForcedOrientation();a=wade.getContainerWidth();g=wade.getContainerHeight();var w=n;switch(u){case "landscape":g>a&&(n=!n);break;case "portrait":a>g&&(n=!n);break;default:n=!1}n!=w&&(u=n?"rotate(90deg)":"translate3d(0, 0, 0)",s.style.MozTransform=u,s.style.msTransform=u,s.style.OTransform=u,s.style.webkitTransform=u,s.style.transform=u);u=!1;a=wade.getContainerWidth();g=wade.getContainerHeight();
var t,k;if("full"==f){var m=c,p=d;c=Math.max(Math.min(a,h),j);d=Math.max(Math.min(g,l),i);c>a||d>g?c/a>d/g?(d=Math.max(Math.min(Math.min(d,g)*c/a,l),i),t=a+"px",k=Math.floor(a*d/c)+"px"):(c=Math.max(Math.min(Math.min(c,a)*d/g,h),j),t=Math.floor(g*c/d)+"px",k=g+"px"):c<a&&d<g?c/a>d/g?(k=Math.floor(a*d/c)+"px",t=a+"px"):(k=g+"px",t=Math.floor(g*c/d)+"px"):(k=d+"px",t=c+"px");if(m!=c||p!=d)s.width=c,s.height=d,e.onResize(m,p,c,d),u=!0}else"stretchToFit"==f&&(a/c>g/d?(t=Math.floor(g*c/d)+"px",k=a+"px"):
(t=a+"px",k=Math.floor(a*d/c)+"px"));if(m=t&&k&&(t!=s.style.width||k!=s.style.height))s.style.width=t,s.style.height=k;for(a=0;a<b.length;a++)g=b[a],n!=w&&g.setCanvasStyleRotation(n?90:0),1!=g.getResolutionFactor()&&t&&k&&t==k&&"auto"==t?g.setCanvasStyleSize(s.width+"px",s.height+"px"):m&&g.setCanvasStyleSize(t,k),u&&g.resize(c,d),g.draw();if(!u)for(a=0;a<b.length;a++)g=b[a],g.flipIfNeeded();q&&(console.timeEnd("Draw"),console.log("Number of draw calls: "+wade.numDrawCalls));e.clearSimulationDirtyState()}};
this.addSprite=function(a){a.getLayer().addSprite(a)};this.removeSprite=function(a){a.getLayer().removeSprite(a)};this._layerSorter=function(a,b){return b.id-a.id};this.getLayer=function(b){this._createLayerIfNeeded(b);return a[b]};this.getLayerSorting=function(b){return a[b].getSorting()};this.setLayerSorting=function(b,c){this._createLayerIfNeeded(b);a[b].setSorting(c)};this.setLayerTransform=function(b,c,q){this._createLayerIfNeeded(b);a[b].setTransform(c,q)};this.setLayerResolutionFactor=function(b,
c){this._createLayerIfNeeded(b);a[b].setResolutionFactor(c)};this.getLayerResolutionFactor=function(b){return a[b]&&a[b].getResolutionFactor()};this.setResolutionFactor=function(a){for(var c=0;c<b.length;c++)b[c].setResolutionFactor(a)};this.setLayerSmoothing=function(b,c){this._createLayerIfNeeded(b);a[b].setSmoothing(c)};this.getLayerSmoothing=function(b){return a[b]&&a[b].getSmoothing()};this.setSmoothing=function(a){p=a;for(a=0;a<b.length;a++)b[a].setSmoothing(p)};this.getSmoothing=function(){return p};
this.getScreenWidth=function(){return c};this.getScreenHeight=function(){return d};this.setScreenSize=function(a,f){if(a!=c||f!=d){c=a;d=f;for(var q=0;q<b.length;q++)b[q].resize(c,d)}};this.getMaxScreenWidth=function(){return h};this.getMaxScreenHeight=function(){return l};this.setMaxScreenSize=function(a,b){h=a;l=b;if(c>h||d>l)e.setSimulationDirtyState(),this.draw()};this.getMinScreenWidth=function(){return j};this.getMinScreenHeight=function(){return i};this.setMinScreenSize=function(a,b){j=a;i=
b;if(c<j||d<i)e.setSimulationDirtyState(),this.draw()};this.setCanvasClearing=function(b,c){this._createLayerIfNeeded(b);a[b].setCanvasClearing(c)};this.setWindowMode=function(a){f=a};this.getWindowMode=function(){return f};this.getCameraPosition=function(){return{x:g,y:k,z:m}};this.setCameraPosition=function(a){g=a.x;k=a.y;m=a.z;for(var c=0;c<b.length;c++)b[c].onCameraPositionChanged(a)};this.worldPositionToScreen=function(a,b){return this.getLayer(a).worldPositionToScreen(b)};this.worldDirectionToScreen=
function(a,b){return this.getLayer(a).worldDirectionToScreen(b)};this.worldBoxToScreen=function(a,b){return this.getLayer(a).worldBoxToScreen(b)};this.screenPositionToWorld=function(a,b){return this.getLayer(a).screenPositionToWorld(b)};this.screenDirectionToWorld=function(a,b){return this.getLayer(a).worldDirectionToScreen(b)};this.screenBoxToWorld=function(a,b){return this.getLayer(a).screenBoxToWorld(b)};this.removeCanvases=function(){for(var a=0;a<b.length;a++)b[a].removeCanvases()};this.enableDoubleBuffering=
function(a){if(a)for(a=0;a<b.length;a++)b[a].createSecondaryCanvas();else for(a=0;a<b.length;a++)b[a].removeSecondaryCanvas()};this.isScreenRotated=function(){return n}}
function SceneManager(){var a=[],b={onMouseDown:[],onMouseUp:[],onMouseMove:[],onMouseWheel:[],onClick:[],onMouseIn:[],onMouseOut:[],onKeyDown:[],onKeyUp:[],onKeyPress:[],onAppTimer:[],onSimulationStep:[],onResize:[]},c=wade.cloneObject(b),d=0,e=!1;this.init=function(){this.renderer=new Renderer;this.renderer.init(this)};this.addSceneObject=function(b){a.push(b);b.addSpritesToRenderer(this.renderer);b.processEvent("onAddToScene")};this.removeEventListener=function(a,c){wade.removeObjectFromArray(a,
b[c])};this.removeGlobalEventListener=function(a,b){wade.removeObjectFromArray(a,c[b])};this.removeSceneObject=function(d){if(d){d.processEvent("onRemoveFromScene");wade.removeObjectFromArray(d,a);for(var e in b)b.hasOwnProperty(e)&&(b[e].length&&this.removeEventListener(d,e),c[e].length&&this.removeGlobalEventListener(d,e));d.removeSpritesFromRenderer()}};this.clear=function(){for(var b=a.length-1;0<=b;b--)this.removeSceneObject(a[b])};this.step=function(){var a=wade.logSimulationTime&&console.time&&
console.timeEnd&&0.02>Math.random();a&&console.time("Simulation");for(var c=b.onSimulationStep,l=0;l<c.length;l++)c[l].step();d+=wade.c_timeStep;a&&console.timeEnd("Simulation");e=!0};this.addEventListener=function(a,c){b[c].push(a)};this.addGlobalEventListener=function(a,b){c[b].push(a)};this.getEventListeners=function(a,c){var d=[],e,i;switch(a){case "onMouseDown":case "onMouseUp":case "onMouseMove":case "onMouseWheel":case "onClick":case "onMouseIn":case "onMouseOut":var g={x:c.screenPosition.x,
y:c.screenPosition.y};for(e=0;e<b[a].length;e++){i=b[a][e];var k=i.getSpriteAtPosition(g);k.isPresent&&(i.eventResponse={spriteIndex:k.spriteIndex,position:k.relativeWorldPosition,screenPosition:g,topLayer:k.topLayer,button:c.button,value:c.value},d.push(i))}d.sort(this.eventListenersSorter);break;default:for(e=0;e<b[a].length;e++)i=b[a][e],i.eventResponse=c,d.push(i)}return d};this.eventListenersSorter=function(a,b){return a.eventResponse.topLayer-b.eventResponse.topLayer};this.onResize=function(b,
c,d,e){for(var i=0;i<a.length;i++){var g=a[i],k=g.getPosition(),m=g.getAlignment(),p=0,n=0;switch(m.x){case "right":p=(d-b)/2;break;case "left":p=-(d-b)/2}switch(m.y){case "top":n=-(e-c)/2;break;case "bottom":n=(e-c)/2}g.setPosition(k.x+p,k.y+n);if(g.isMoving()&&(p||n))k=g.getTargetPosition(),g.moveTo(k.x+p,k.y+n,g.getMovementSpeed())}b={width:d,height:e};this.processEvent("onResize",b)||wade.app.onResize&&wade.app.onResize(b)};this.processEvent=function(a,b){for(var d=this.getEventListeners(a,b),
e=!1,i=0;i<d.length;i++){var g=d[i];if(g.processEvent(a,g.eventResponse)){e=!0;break}}d=wade.cloneObject(b);d.global=!0;for(i=0;i<c[a].length;i++)c[a][i].processEvent(a,d);return e};this.appTimerEvent=function(){for(var a=0;a<b.onAppTimer.length;a++)b.onAppTimer[a].processEvent("onAppTimer")};this.updateMouseInOut=function(a,b){var c,d,e="undefined"!=typeof a.x;if(e){var g=this.getEventListeners("onMouseOut",{screenPosition:a});for(c=0;c<g.length&&!(d=g[c],!d.getSpriteAtPosition(b).isPresent&&d.processEvent("onMouseOut",
d.eventResponse));c++);}g=this.getEventListeners("onMouseIn",{screenPosition:b});for(c=0;c<g.length&&!(d=g[c],(!e||!d.getSpriteAtPosition(a).isPresent)&&d.processEvent("onMouseIn",d.eventResponse));c++);};this.getAppTime=function(){return d};this.getSimulationDirtyState=function(){return e};this.clearSimulationDirtyState=function(){e=!1};this.setSimulationDirtyState=function(){e=!0};this.draw=function(){this.renderer.draw()}}
function SceneObject(a,b,c,d){this._position={x:c?c:0,y:d?d:0};this._behaviorClasses=b;this._behaviors=[];this._sprites=a;this._spriteOffsets=[];this._moving=!1;this._linearVelocity={x:0,y:0};this._targetPosition=this._position;this._alignment={x:0,y:0};this._animationsPlaying=0;this._inScene=!1;this._rotation=this._renderer=0;if(this._sprites){jQuery.isArray(this._sprites)||(this._sprites=[this._sprites]);for(a=0;a<this._sprites.length;a++)this._sprites[a].setSceneObject(this),this._sprites[a].setPosition(this._position),
this._spriteOffsets.push({x:0,y:0})}else this._sprites=[];if(this._behaviorClasses){jQuery.isArray(this._behaviorClasses)||(this._behaviorClasses=[this._behaviorClasses]);for(a=0;a<this._behaviorClasses.length;a++)this._behaviors[a]=new this._behaviorClasses[a],this._behaviors[a].owner=this}}
SceneObject.prototype.setPosition=function(a,b){var c,d;"object"==typeof a?(c=a.x,d=a.y):(c=a,d=b);this._position.x=c;this._position.y=d;for(c=0;c<this._sprites.length;c++)this._sprites[c].setPosition(this._position.x+this._spriteOffsets[c].x,this._position.y+this._spriteOffsets[c].y)};SceneObject.prototype.getPosition=function(){return{x:this._position.x,y:this._position.y}};SceneObject.prototype.setRotation=function(a){this._rotation=a;for(var b=0;b<this._sprites.length;b++)this._sprites[b].setRotation(a)};
SceneObject.prototype.getRotation=function(){return this._rotation};SceneObject.prototype.moveTo=function(a,b,c){this._targetPosition={x:a,y:b};var d=a-this._position.x,e=b-this._position.y,f=Math.sqrt(d*d+e*e);f>c*wade.c_timeStep?(this._linearVelocity={x:d*c/f,y:e*c/f},!this._animationsPlaying&&!this._moving&&wade.simulateSceneObject(this,!0),this._moving=!0):(this.setPosition(a,b),this.stopMoving())};
SceneObject.prototype.stopMoving=function(){!this._animationsPlaying&&this._moving&&wade.simulateSceneObject(this,!1);this._moving=!1;this._targetPosition={x:this._position.x,y:this._position.y};this._linearVelocity={x:0,y:0};this.processEvent("onMoveComplete")};
SceneObject.prototype.step=function(){if(this._moving){var a=this._position.x-this._targetPosition.x,b=this._position.y-this._targetPosition.y;(this._linearVelocity.x*this._linearVelocity.x+this._linearVelocity.y*this._linearVelocity.y)*wade.c_timeStep*wade.c_timeStep<a*a+b*b?this.setPosition(this._position.x+this._linearVelocity.x*wade.c_timeStep,this._position.y+this._linearVelocity.y*wade.c_timeStep):(this.setPosition(this._targetPosition.x,this._targetPosition.y),this.stopMoving())}if(this._animationsPlaying)for(a=
0;a<this._sprites.length;a++)this._sprites[a].step()};SceneObject.prototype.playAnimation=function(a,b){for(var c=0;c<this._sprites.length;c++)this._sprites[c].playAnimation(a,b)};SceneObject.prototype.getBehavior=function(a){if(a){for(var b=0;b<this._behaviors.length;b++)if(this._behaviors[b].name==a)return this._behaviors[b];return null}return this._behaviors[0]};SceneObject.prototype.getAlignment=function(){return{x:this._alignment.x,y:this._alignment.y}};
SceneObject.prototype.setAlignment=function(a,b){this._alignment.x=a;this._alignment.y=b};
SceneObject.prototype.processEvent=function(a,b){switch(a){case "onAnimationStart":!this._animationsPlaying&&!this._moving&&wade.simulateSceneObject(this,!0);b.restarting||this._animationsPlaying++;break;case "onAnimationEnd":1==this._animationsPlaying&&!this._moving&&wade.simulateSceneObject(this,!1),this._animationsPlaying--}var c=!1;this[a]&&(c=this[a](b));for(var d=0;d<this._behaviors.length;d++)this._behaviors[d][a]&&(c=c||this._behaviors[d][a](b));return c};
SceneObject.prototype.getSpriteAtPosition=function(a){for(var b={isPresent:!1,topLayer:9999,spriteIndex:0},c=0;c<this._sprites.length;c++){var d=this._sprites[c],e=d.getLayer().getResolutionFactor();if(d.containsScreenPoint({x:a.x*e,y:a.y*e})&&d.isVisible()){var e=d.getLayer(),f=!b.isPresent||e.id<b.topLayer;e.id==b.topLayer&&b.isPresent&&(f=0<e.compareSprites(d,this._sprites[b.spriteIndex]));f&&(b={isPresent:!0,topLayer:e.id,spriteIndex:c},d=d.getWorldOffset(a),e=this._spriteOffsets[c],d.x+=e.x,
d.y+=e.y,b.relativeWorldPosition=d)}}return b};SceneObject.prototype.setSpriteOffsets=function(a){this._spriteOffsets=jQuery.isArray(a)?a:[a];for(a=0;a<this._spriteOffsets.length;a++)this._sprites[a]&&this._sprites[a].setPosition(this._position.x+this._spriteOffsets[a].x,this._position.y+this._spriteOffsets[a].y)};SceneObject.prototype.getSpriteOffset=function(a){return{x:this._spriteOffsets[a].x,y:this._spriteOffsets[a].y}};
SceneObject.prototype.setSpriteOffset=function(a,b){this._spriteOffsets[a].x=b.x;this._spriteOffsets[a].y=b.y;this._sprites[a]&&this._sprites[a].setPosition(this._position.x+this._spriteOffsets[a].x,this._position.y+this._spriteOffsets[a].y)};SceneObject.prototype.isMoving=function(){return this._moving};SceneObject.prototype.setVisible=function(a){for(var b=0;b<this._sprites.length;b++)this._sprites[b].setVisible(a)};
SceneObject.prototype.addSprite=function(a,b){a.setSceneObject(this);this._sprites.push(a);b?(this._spriteOffsets.push({x:b.x,y:b.y}),a.setPosition(this._position.x+b.x,this._position.y+b.y)):(this._spriteOffsets.push({x:0,y:0}),a.setPosition(this._position.x,this._position.y));this._inScene&&this._renderer.addSprite(a);return this._sprites.length-1};
SceneObject.prototype.removeSpriteByIndex=function(a){this._renderer.removeSprite(this._sprites[a]);wade.removeObjectFromArrayByIndex(a,this._sprites);wade.removeObjectFromArrayByIndex(a,this._spriteOffsets)};SceneObject.prototype.removeSprite=function(a){for(var b=0;b<this._sprites.length;b++)if(this._sprites[b]==a){this.removeSpriteByIndex(b);break}};
SceneObject.prototype.removeAllSprites=function(){for(var a=this._sprites.length-1;0<=a;a--)this._renderer.removeSprite(this._sprites[a]);this._spriteOffsets.length=0;this._sprites.length=0};SceneObject.prototype.updateSpriteOffset=function(a,b){this._spriteOffsets[a].x=b.x;this._spriteOffsets[a].y=b.y;this._sprites[a].setPosition(this._position.x+b.x,this._position.y+b.y)};SceneObject.prototype.getSprite=function(a){return this._sprites[a?a:0]};SceneObject.prototype.isInScene=function(){return this._inScene};
SceneObject.prototype.getSpriteCount=function(){return this._sprites.length};SceneObject.prototype.addBehavior=function(a){this._behaviorClasses?this._behaviorClasses.push(a):this._behaviorClasses=[a];a=new a;a.owner=this;this._behaviors.push(a);return a};SceneObject.prototype.removeBehavior=function(a){for(var b=0;b>this._behaviors.length;b++)if(a==this._behaviors[b].name)return wade.removeObjectFromArrayByIndex(b,this._behaviors[b]),!0;return!1};
SceneObject.prototype.isAnimating=function(){return this._animationsPlaying?!0:!1};SceneObject.prototype.getTargetPosition=function(){return{x:this._targetPosition.x,y:this._targetPosition.y}};SceneObject.prototype.getMovementSpeed=function(){return Math.sqrt(this._linearVelocity.x*this._linearVelocity.x+this._linearVelocity.y*this._linearVelocity.y)};SceneObject.prototype.overlapsSprite=function(a){for(var b=0;b<this._sprites.length;b++)if(this._sprites[b].overlapsSprite(a))return!0;return!1};
SceneObject.prototype.overlapsObject=function(a){for(var b=a.getSpriteCount(),c=0;c<b;c++)if(this.overlapsSprite(a.getSprite(c)))return!0;return!1};
SceneObject.prototype.clone=function(){var a=new SceneObject;jQuery.extend(a,this);a._inScene=0;a._sprites=[];for(var b=0;b<this._sprites.length;b++){var c=this._sprites[b].clone();c._sceneObject=a;a._sprites.push(c)}a._position={x:this._position.x,y:this._position.y};a._linearVelocity={x:this._linearVelocity.x,y:this._linearVelocity.y};a._targetPosition={x:this._targetPosition.x,y:this._targetPosition.y};a._alignment={x:this._alignment.x,y:this._alignment.y};a._spriteOffsets=jQuery.extend(!0,[],
this._spriteOffsets);a._behaviors=[];for(b=0;b<a._behaviorClasses.length;b++)a._behaviors[b]=new this._behaviorClasses[b],a._behaviors[b].owner=a;this.simulated&&(a.simulated=!1,wade.simulateSceneObject(a,!0));return a};SceneObject.prototype.addSpritesToRenderer=function(a){this._inScene=!0;this._renderer=a;for(var b=0;b<this._sprites.length;b++)a.addSprite(this._sprites[b])};
SceneObject.prototype.removeSpritesFromRenderer=function(){if(this._inScene){this._inScene=!1;for(var a=0;a<this._sprites.length;a++)this._sprites[a].isVisible()&&this._sprites[a].setDirtyArea(),this._renderer.removeSprite(this._sprites[a])}};
function Sprite(a,b){this._sceneObject=null;this._animations={};this._currentAnimation="default";this._position={x:0,y:0};this._sortPoint={x:0,y:0};this._layer=wade.getLayer(b?b:1);var c=new Animation(a);c.sprite=this;c.name=this._currentAnimation;this._animations[this._currentAnimation]=c;this._numAnimations=1;this._size=this._animations[this._currentAnimation].getImageSize();this._visible=!0;this._image=wade.getImage(a);this._rotation=this._cornerY=this._cornerX=0;this.boundingBox={};this.draw=
this.drawStatic;this.updateBoundingBox()}Sprite.prototype.setPosition=function(a,b){var c,d;"object"==typeof a?(c=a.x,d=a.y):(c=a,d=b);this.setDirtyArea();this._position.x=c;this._position.y=d;this.updateBoundingBox();this._cornerX=c-this._size.x/2;this._cornerY=d-this._size.y/2;this.setDirtyArea();this._layer.onSpritePositionChanged(this)};Sprite.prototype.getPosition=function(){return{x:this._position.x,y:this._position.y}};
Sprite.prototype.setRotation=function(a){this.setDirtyArea();this._rotation=a;this.updateBoundingBox();this.setDirtyArea()};Sprite.prototype.getRotation=function(){return this._rotation};Sprite.prototype.setSize=function(a,b){if(a!=this._size.x||b!=this._size.y)this.setDirtyArea(),this._size={x:a,y:b},this._cornerX=this._position.x-a/2,this._cornerY=this._position.y-b/2,this.updateBoundingBox(),this.setDirtyArea()};Sprite.prototype.getSize=function(){return{x:this._size.x,y:this._size.y}};
Sprite.prototype.setSortPoint=function(a,b){this._sortPoint.x=a;this._sortPoint.y=b};Sprite.prototype.getSortPoint=function(){return{x:this._sortPoint.x,y:this._sortPoint.y}};Sprite.prototype.addAnimation=function(a,b){this._animations[a]||this._numAnimations++;this._animations[a]=b;b.name=a;b.sprite=this;1==this._numAnimations&&(this.playAnimation(a),this.updateBoundingBox());this.draw==this.drawStatic&&(this.draw=this.drawAnimated)};
Sprite.prototype.playAnimation=function(a,b){this._animations[a]&&(a!=this._currentAnimation&&this.setDirtyArea(),this._currentAnimation=a,this._animations[a].play(b))};Sprite.prototype.step=function(){var a=this._animations[this._currentAnimation];a&&a.isPlaying()&&a.step()};
Sprite.prototype.setSceneObject=function(a){if(a!=this._sceneObject){var b=this._animations[this._currentAnimation];b&&b.isPlaying()&&(a&&a.processEvent("onAnimationStart",this._currentAnimation),this._sceneObject&&this._sceneObject.processEvent("onAnimationEnd",this._currentAnimation));this._sceneObject=a}};
Sprite.prototype.getScreenPositionAndExtents=function(){var a=this._layer.worldDirectionToScreen(this.getSize()),b=this._layer.worldPositionToScreen(this._position);return{extents:{x:a.x/2,y:a.y/2},position:b}};Sprite.prototype.containsScreenPoint=function(a){var b=this.getScreenPositionAndExtents(),c=b.position.y-b.extents.y,d=b.position.x+b.extents.x,e=b.position.y+b.extents.y;return a.x>=b.position.x-b.extents.x&&a.x<=d&&a.y>=c&&a.y<=e};
Sprite.prototype.getWorldOffset=function(a){a=this._layer.screenPositionToWorld(a);return{x:a.x-this._position.x,y:a.y-this._position.y}};Sprite.prototype.setDirtyArea=function(){this._layer.addDirtyArea({minX:this.boundingBox.minX,minY:this.boundingBox.minY,maxX:this.boundingBox.maxX,maxY:this.boundingBox.maxY})};Sprite.prototype.setVisible=function(a){a!=this._visible&&(this._visible=a,this.setDirtyArea())};Sprite.prototype.isVisible=function(){return this._visible};
Sprite.prototype.setImageFile=function(a,b){this.setDirtyArea();this._animations[this._currentAnimation]=new Animation(a,1,1,0);b&&(this._size=this._animations[this._currentAnimation].getImageSize(),this._cornerX=this._position.x-this._size.x/2,this._cornerY=this._position.y-this._size.y/2);this._image=wade.getImage(a);this.setDirtyArea()};Sprite.prototype.bringToFront=function(){this._layer.bringSpriteToFront(this)};Sprite.prototype.pushToBack=function(){this._layer.pushSpriteToBack(this)};
Sprite.prototype.getCurrentAnimation=function(){return this._animations[this._currentAnimation]};Sprite.prototype.getCurrentAnimationName=function(){return this._currentAnimation};Sprite.prototype.hasAnimation=function(a){return this._animations[a]?!0:!1};Sprite.prototype.setDrawFunction=function(a){this.draw=a;this.setDirtyArea()};
Sprite.prototype.overlapsSprite=function(a){var b=this._layer.id,c=a.getLayer().id;if(b==c)return wade.boxIntersectsBox(this.boundingBox,a.boundingBox);b=wade.worldBoxToScreen(b,this.boundingBox);a=wade.worldBoxToScreen(c,a.boundingBox);return wade.boxIntersectsBox(b,a)};Sprite.prototype.getImageName=function(){return this._animations[this._currentAnimation].getImageName()};
Sprite.prototype.setLayer=function(a){this._sceneObject&&this._sceneObject.isInScene()?(this._layer&&this._layer.removeSprite(this),this._layer=wade.getLayer(a?a:1),this._layer.addSprite(this)):this._layer=wade.getLayer(a?a:1)};
Sprite.prototype.drawToImage=function(a,b,c,d,e){var f=c||{x:0,y:0},c=document.createElement("canvas"),h=c.getContext("2d");b||"ok"!=wade.getLoadingStatus(a)?(c.width=this.boundingBox.maxX-this.boundingBox.minX+Math.abs(f.x),c.height=this.boundingBox.maxY-this.boundingBox.minY+Math.abs(f.y)):(b=wade.getImage(a),c.width=b.width,c.height=b.height,h.drawImage(b,0,0));b=this._position;this._position.x=f.x+c.width/2;this._position.y=f.y+c.height/2;this._cornerX=this._position.x-this._size.x/2;this._cornerY=
this._position.y-this._size.y/2;f=h.globalCompositeOperation;e&&(h.globalCompositeOperation=e);d?(h.save(),h.setTransform(d.horizontalScale,d.horizontalSkew,d.verticalSkew,d.verticalScale,d.horizontalTranslate,d.verticalTranslate),this.draw(h),h.restore()):this.draw(h);h.globalCompositeOperation=f;this._position=b;this._cornerX=this._position.x-this._size.x/2;this._cornerY=this._position.y-this._size.y/2;wade.setImage(a,c)};
Sprite.prototype.stopAnimation=function(){var a=this._animations[this._currentAnimation];a&&a.stop()};Sprite.prototype.resumeAnimation=function(){var a=this._animations[this._currentAnimation];a&&a.resume()};
Sprite.prototype.clone=function(){var a=new Sprite;jQuery.extend(a,this);a._sceneObject=0;a.quadTreeNode=0;if(this._animations){a._animations={};for(var b in this._animations)this._animations.hasOwnProperty(b)&&(a._animations[b]=this._animations[b].clone(),a._animations[b].sprite=a)}a._position={x:this._position.x,y:this._position.y};a._sortPoint={x:this._sortPoint.x,y:this._sortPoint.y};a._size={x:this._size.x,y:this._size.y};a.boundingBox=jQuery.extend({},this.boundingBox);return a};
Sprite.prototype.getLayer=function(){return this._layer};Sprite.prototype.onAnimationStart=function(a,b){this._sceneObject&&this._sceneObject.processEvent("onAnimationStart",{name:a,restarting:b})};Sprite.prototype.onAnimationEnd=function(a){this._sceneObject&&this._sceneObject.processEvent("onAnimationEnd",{name:a})};
Sprite.prototype.updateBoundingBox=function(){var a=this.getSize();a.x/=2;a.y/=2;if(this._rotation){var b=Math.cos(this._rotation),c=Math.sin(this._rotation),d=a.x*b,e=a.x*c,c=a.y*c,f=a.y*b,b=Math.abs(d+c),a=Math.abs(e-f),d=Math.abs(d-c),e=Math.abs(e+f),d=Math.max(b,d),e=Math.max(a,e);this.boundingBox.minX=this._position.x-d;this.boundingBox.minY=this._position.y-e;this.boundingBox.maxX=this._position.x+d;this.boundingBox.maxY=this._position.y+e}else this.boundingBox.minX=this._position.x-a.x,this.boundingBox.minY=
this._position.y-a.y,this.boundingBox.maxX=this._position.x+a.x,this.boundingBox.maxY=this._position.y+a.y};Sprite.prototype.drawStatic=function(a){this._visible&&(wade.numDrawCalls++,this._rotation&&(a.save(),a.translate(this._position.x,this._position.y),a.rotate(this._rotation),a.translate(-this._position.x,-this._position.y)),a.drawImage(this._image,this._cornerX,this._cornerY,this._size.x,this._size.y),this._rotation&&a.restore())};
Sprite.prototype.drawAnimated=function(a){if(this._visible){var b=this._animations[this._currentAnimation];b&&(this._rotation&&(a.save(),a.translate(this._position.x,this._position.y),a.rotate(this._rotation),a.translate(-this._position.x,-this._position.y)),b.draw(a,this._position,this._size),this._rotation&&a.restore())}};Sprite.prototype.draw=Sprite.prototype.drawAnimated;
function TextSprite(a,b,c,d,e){this._sceneObject=0;this._position={x:0,y:0};this._sortPoint={x:0,y:0};this._layer=wade.getLayer(e?e:1);this._font=b||"12px Arial";this._alignment=d||"left";this._size={x:0,y:0};this._color=c||"#000";this._visible=!0;this._shadowBlur=this._shadowColor=this._maxWidth=0;this._shadowOffset={x:0,y:0};this._numLines=this._lineSpacing=1;this._maxLines=0;this._lines=[];this._outlineColor="#000";this._rotation=this._outlineWidth=0;this.boundingBox={minX:0,minY:0,maxX:0,maxY:0};
this.setText(a?a:"")}TextSprite.prototype.setPosition=Sprite.prototype.setPosition;TextSprite.prototype.getPosition=Sprite.prototype.getPosition;TextSprite.prototype.setSortPoint=Sprite.prototype.setSortPoint;TextSprite.prototype.getSortPoint=Sprite.prototype.getSortPoint;TextSprite.prototype.getLayer=Sprite.prototype.getLayer;TextSprite.prototype.getScreenPositionAndExtents=Sprite.prototype.getScreenPositionAndExtents;TextSprite.prototype.getScreenBox=Sprite.prototype.getScreenBox;
TextSprite.prototype.containsScreenPoint=Sprite.prototype.containsScreenPoint;TextSprite.prototype.getWorldOffset=Sprite.prototype.getWorldOffset;TextSprite.prototype.setDirtyArea=Sprite.prototype.setDirtyArea;TextSprite.prototype.updateBoundingBox=Sprite.prototype.updateBoundingBox;TextSprite.prototype.setVisible=Sprite.prototype.setVisible;TextSprite.prototype.isVisible=Sprite.prototype.isVisible;TextSprite.prototype.bringToFront=Sprite.prototype.bringToFront;TextSprite.prototype.pushToBack=Sprite.prototype.pushToBack;
TextSprite.prototype.setDrawFunction=Sprite.prototype.setDrawFunction;TextSprite.prototype.overlapsSprite=Sprite.prototype.overlapsSprite;TextSprite.prototype.drawToImage=Sprite.prototype.drawToImage;TextSprite.prototype.setRotation=Sprite.prototype.setRotation;TextSprite.prototype.setText=function(a){this.setDirtyArea();this._text=a.toString();this._updateSize();this.setDirtyArea()};TextSprite.prototype.getText=function(){return this._text};
TextSprite.prototype.setMaxWidth=function(a){this._maxWidth=a;this._updateSize()};TextSprite.prototype.setMaxLines=function(a){if(this._maxLines!=a){if(this._maxLines=a)this._numLines=Math.min(this._numLines,this._maxLines);this._updateSize()}};TextSprite.prototype.setColor=function(a){this._color=a;this.setDirtyArea()};TextSprite.prototype.setShadow=function(a,b,c,d){this._shadowColor=a;this._shadowBlur=b;this._shadowOffset={x:c?c:0,y:d?d:0};this.setDirtyArea();this._updateSize();this.setDirtyArea()};
TextSprite.prototype.setFont=function(a){this._font=a;this.setDirtyArea();this._updateSize();this.setDirtyArea()};TextSprite.prototype.setLineSpacing=function(a){this._lineSpacing=a;this.setDirtyArea();this._updateSize();this.setDirtyArea()};TextSprite.prototype.setAlignment=function(a){this._alignment=a;this.setDirtyArea();this._updateSize();this.setDirtyArea()};TextSprite.prototype.getLine=function(a){return this._lines[a].text};TextSprite.prototype.getNumLines=function(){return this._numLines};
TextSprite.prototype.getLineWidth=function(a){return this._lines[a].width};TextSprite.prototype.setOutline=function(a,b){this._outlineWidth=a;this._outlineColor=b||"#000"};TextSprite.prototype.clone=function(){var a=new TextSprite;jQuery.extend(a,this);return a};TextSprite.prototype.getSize=function(){return{x:this._size.x,y:this._size.y}};
TextSprite.prototype._updateSize=function(){var a=this._layer.getContext();this._lines.length=0;a.save();this._refresh(0,this._lines,a);this._numLines=this._lines.length;for(var b=0,c=0;c<this._lines.length;c++)b=Math.max(b,this._lines[c].width);this._size.x=b;this._size.y=3*a.measureText("m").width+this._outlineWidth;this._size.y*=this._numLines*this._lineSpacing;1<this._numLines&&(this._size.y*=2);"center"!=this._alignment&&(this._size.x*=2);this._shadowColor&&(this._size.x+=Math.abs(this._shadowOffset.x)+
Math.max(8,2*this._shadowBlur),this._size.y+=Math.abs(this._shadowOffset.y)+Math.max(8,2*this._shadowBlur));this._outlineWidth&&(this._size.x+=this._outlineWidth,this._size.y+=this._outlineWidth);a.restore();this.updateBoundingBox()};TextSprite.prototype.draw=function(a){this._visible&&this._text&&this._refresh(1,0,a)};TextSprite.prototype.step=function(){};TextSprite.prototype.playAnimation=function(){};TextSprite.prototype.setSceneObject=function(a){this._sceneObject=a};
TextSprite.prototype._refresh=function(a,b,c){c=c||this._layer.getContext();this._rotation&&(c.save(),c.translate(this._position.x,this._position.y),c.rotate(this._rotation),c.translate(-this._position.x,-this._position.y));c.font=this._font;c.fillStyle=this._color;c.textAlign=this._alignment;this._shadowColor&&(c.shadowColor=this._shadowColor,c.shadowBlur=this._shadowBlur,c.shadowOffsetX=this._shadowOffset.x,c.shadowOffsetY=this._shadowOffset.y);if(this._outlineWidth){var d=c.strokeStyle,e=c.lineWidth;
c.lineWidth=this._outlineWidth;c.strokeStyle=this._outlineColor}if(!this._maxWidth&&0>this._text.indexOf("\n"))a&&(c.fillText(this._text,this._position.x,this._position.y),this._outlineWidth&&c.strokeText(this._text,this._position.x,this._position.y)),b&&b.push({width:c.measureText(this._text).width+this._outlineWidth,text:this._text});else{for(var f=0,h=this._text.split("\n"),l=0;l<h.length&&(!this._maxLines||f<this._maxLines);l++){for(var j=h[l].split(" "),i=1,g,k=2*c.measureText("m").width+this._outlineWidth;0<
j.length&&i<=j.length&&(!this._maxLines||f<this._maxLines);)g=j.slice(0,i).join(" "),c.measureText(g).width+this._outlineWidth>this._maxWidth&&0<this._maxWidth?(1==i&&(i=2),g=j.slice(0,i-1).join(" "),a&&(c.fillText(g,this._position.x,this._position.y+k*this._lineSpacing*f),this._outlineWidth&&c.strokeText(this._text,this._position.x,this._position.y)),b&&b.push({width:c.measureText(g).width+this._outlineWidth,text:g}),f++,j=j.splice(i-1),i=1):i++;0<i&&(g=j.join(" "),a&&(c.fillText(g,this._position.x,
this._position.y+k*this._lineSpacing*f),this._outlineWidth&&c.strokeText(this._text,this._position.x,this._position.y)),b&&b.push({width:c.measureText(g).width+this._outlineWidth,text:g}),f++)}this._numLines=f}this._shadowColor&&(c.shadowColor="rgba(0, 0, 0, 0)");this._outlineWidth&&(c.strokeStyle=d,c.lineWidth=e);this._rotation&&c.restore()};
function Wade(){var a=0,b=0,c=0,d=0,e=0,f=0,h=!1,l=!1,j="",i=1,g=[],k=[],m=0,p=!1,n=1,r="none",v=new Image;v.src="data:image/gif;base64,R0lGODlhAQABAIAAAP7//wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==";this.app=0;this.c_timeStep=1/30;this._appData=0;this.c_epsilon=1E-4;this.init=function(q,s,e,f){var g=function(){var a=window.applicationCache;if(a)if(a.status==a.UPDATEREADY)console.log("a new version is available"),f?f():(alert("A new version is available.\nPlease press OK to restart."),a.swapCache(),
window.location.reload(!0),window.location=window.location);else{try{a.update()}catch(b){}a.addEventListener("updateready",g,!1)}};g();q&&(j=q.substr(0,Math.max(q.lastIndexOf("/"),q.lastIndexOf("\\"))+1));for(var h=0,i=["ms","moz","webkit","o"],k=0;k<i.length&&!window.requestAnimationFrame;k++)window.requestAnimationFrame=window[i[k]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[i[k]+"CancelAnimationFrame"]||window[i[k]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=
function(a){var b=(new Date).getTime(),c=Math.max(0,16-(b-h)),q=window.setTimeout(function(){a(b+c)},c);h=b+c;return q});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(a){clearTimeout(a)});b=new AssetLoader;b.init();c=new AssetLoader;c.init();a=new SceneManager;a.init();d=new InputManager;d.init();this._appData=s?s:{};q?b.loadAppScript(q,e):App?this.instanceApp():console.log("Warning - App is not defined.");this.event_mainLoop()};this.stop=function(){e&&cancelAnimationFrame(e);
f&&clearTimeout(f)};this.stopInputEvents=function(){d.deinit()};this.getRelativeAppPath=function(){return j};this.getFullPathAndFileName=function(a){return"http://"==a.substr(0,7).toLowerCase()||"https://"==a.substr(0,8).toLowerCase()||"//"==a.substr(0,2).toLowerCase()?a:j+a};this.loadScript=function(a,c,d,e){a=this.getFullPathAndFileName(a);b.loadScript(a,c,d,e)};this.preloadScript=function(a,b,d,e){a=this.getFullPathAndFileName(a);c.loadScript(a,b,d,e)};this.loadJson=function(a,c,d,e,f){a=this.getFullPathAndFileName(a);
b.loadJson(a,c,d,e,f)};this.preloadJson=function(a,b,d,e,f){a=this.getFullPathAndFileName(a);c.loadJson(a,b,d,e,f)};this.loadImage=function(a,c,d){a=this.getFullPathAndFileName(a);b.loadImage(a,c,d)};this.preloadImage=function(a,b,d){a=this.getFullPathAndFileName(a);c.loadImage(a,b,d)};this.unloadImage=function(a){a=this.getFullPathAndFileName(a);b.unloadImage(a);c.unloadImage(a)};this.unloadAllImages=function(){b.unloadAllImages();c.unloadAllImages()};this.getImage=function(a){return a?(a=this.getFullPathAndFileName(a),
b.getImage(a)):v};this.setImage=function(a,c){var d=this.getFullPathAndFileName(a);b.setImage(d,c)};this.loadAudio=function(a,c,d,e,f){a=this.getFullPathAndFileName(a);b.loadAudio(a,c,d,e,f)};this.preloadAudio=function(a,b,d,e,f){a=this.getFullPathAndFileName(a);c.loadAudio(a,b,d,e,f)};this.unloadAudio=function(a){a=this.getFullPathAndFileName(a);b.unloadAudio(a);c.unloadAudio(a)};this.unloadAllAudio=function(){b.unloadAllAudio();c.unloadAllAudio()};this.setAudio=function(a,c){var d=this.getFullPathAndFileName(a);
b.setAudio(d,c)};this.playAudio=function(a,c){var d=this.getAudio(this.getFullPathAndFileName(a)),e=b.getWebAudioContext();if(e){var f=e.createBufferSource();f.buffer=d;f.loop=!!c;f.connect(e.destination);f.start(0)}else d.alreadyPlayed&&!d.ended&&(d=new Audio(d.src)),d.loop=c,d.alreadyPlayed=!0,c&&d.addEventListener("ended",function(){this.currentTime=0;this.play()},!1),d.play()};this.playAudioIfAvailable=function(a,b){"ok"==this.getLoadingStatus(this.getFullPathAndFileName(a))&&this.playAudio(a,
b)};this.playAudioSegment=function(a,c,d,e){a=this.getAudio(this.getFullPathAndFileName(a));if(c=b.getWebAudioContext()){var f=c.createBufferSource();f.buffer=a;f.connect(c.destination);e&&(f.onended=e);f.start(0);f.stop(d)}else d=d||a.duration,a.alreadyPlayed&&!a.ended&&(a=new Audio(a.src)),a.addEventListener("timeupdate",function(){this.currentTime>=d&&(this.pause(),this.ended=!0,e&&e())},!1),a.alreadyPlayed=!0,a.play()};this.playAudioSegmentIfAvailable=function(a,b,c,d){"ok"==this.getLoadingStatus(this.getFullPathAndFileName(a))&&
this.playAudioSegment(a,b,c,d)};this.getLoadingStatus=function(a){a=this.getFullPathAndFileName(a);return b.getLoadingStatus(a)};this.instanceApp=function(){this.app=new App;this.app.appData=this._appData;this.app.load&&this.app.load();l=!0};this.initializeApp=function(){h=!0;this.app.init?(this.app.init(),f=setTimeout("wade.event_appTimerEvent();",1E3*i)):console.log("Warning: Unable to initialize app. App.init function is missing.")};this.processEvent=function(b,c){return a.processEvent(b,c)};this.addEventListener=
function(b,c){a.addEventListener(b,c)};this.removeEventListener=function(b,c){a.removeEventListener(b,c)};this.addGlobalEventListener=function(b,c){a.addGlobalEventListener(b,c)};this.removeGlobalEventListener=function(b,c){a.removeGlobalEventListener(b,c)};this.getCameraPosition=function(){return a.renderer.getCameraPosition()};this.setCameraPosition=function(b){a.renderer.setCameraPosition(b)};this.getAppTime=function(){return a.getAppTime()};this.setAppTimerInterval=function(a){i=a};this.removeObjectFromArrayByIndex=
function(a,b){if(0<=a){var c=b.slice(a+1||b.length);b.length=a;return b.push.apply(b,c)}return b};this.removeObjectFromArray=function(a,b){var c=b.lastIndexOf(a);return-1!=c?this.removeObjectFromArrayByIndex(c,b):b};this.addSceneObject=function(b){a.addSceneObject(b)};this.removeSceneObject=function(b){a.removeSceneObject(b)};this.clearScene=function(){a.clear()};this.getLayerSorting=function(b){return a.renderer.getLayerSorting(b)};this.setLayerSorting=function(b,c){a.renderer.setLayerSorting(b,
c)};this.setLayerTransform=function(b,c,d){a.renderer.setLayerTransform(b,c,d)};this.setLayerResolutionFactor=function(b,c){a.renderer.setLayerResolutionFactor(b,c)};this.getLayerResolutionFactor=function(b){return a.renderer.getLayerResolutionFactor(b)};this.setResolutionFactor=function(b){n=b;a.renderer.setResolutionFactor(n)};this.getResolutionFactor=function(){return n};this.getScreenWidth=function(){return a.renderer.getScreenWidth()};this.getScreenHeight=function(){return a.renderer.getScreenHeight()};
this.setScreenSize=function(b,c){a.renderer.setScreenSize(b,c)};this.getContainerWidth=function(){return this.isScreenRotated()?window.innerHeight:window.innerWidth};this.getContainerHeight=function(){return this.isScreenRotated()?window.innerWidth:window.innerHeight};this.setCanvasClearing=function(b,c){a.renderer.setCanvasClearing(b,c)};this.setWindowMode=function(b){a.renderer.setWindowMode(b)};this.loadPage=function(a){self.location=a};this.cloneObject=function(a){return jQuery.extend(!0,{},a)};
this.cloneArray=function(a){return jQuery.extend(!0,[],a)};this.simulateSceneObject=function(b,c){c?b.simulated||(a.addEventListener(b,"onSimulationStep"),b.simulated=!0):b.simulated&&(a.removeEventListener(b,"onSimulationStep"),b.simulated=!1)};this.setMaxScreenSize=function(b,c){a.renderer.setMaxScreenSize(b,c)};this.getMaxScreenWidth=function(){return a.renderer.getMaxScreenWidth()};this.getMaxScreenHeight=function(){return a.renderer.getMaxScreenHeight()};this.setMinScreenSize=function(b,c){return a.renderer.setMinScreenSize(b,
c)};this.getMinScreenWidth=function(){return a.renderer.getMinScreenWidth()};this.getMinScreenHeight=function(){return a.renderer.getMinScreenHeight()};this.createCanvas=function(a){var a=a||1,b=document.getElementById("canvas"),c=document.createElement("canvas");c.width=Math.round(b.width*a);c.height=Math.round(b.height*a);c.style.position=b.style.position;c.style.margin=b.style.margin;c.style.top=b.style.top;c.style.left=b.style.left;c.style.right=b.style.right;c.style.bottom=b.style.bottom;var a=
c.style.width.toString().toLowerCase(),d=c.style.height.toString().toLowerCase();a==d&&"auto"==a?(c.style.width=b.width+"px",c.style.height=b.height+"px"):(c.style.width=b.style.width,c.style.height=b.style.height);c.style.MozTransform=b.style.MozTransform;c.style.msTransform=b.style.msTransform;c.style.OTransform=b.style.OTransform;c.style.webkitTransform=b.style.webkitTransform;c.style.transform=b.style.transform;document.body.appendChild(c);return c};this.deleteCanvases=function(){a.renderer.removeCanvases()};
this.boxContainsBox=function(a,b){return a.minX<b.minX&&a.maxX>b.maxX&&a.minY<b.minY&&a.maxY>b.maxY};this.boxIntersectsBox=function(a,b){return!(a.maxX<b.minX||a.minX>b.maxX||a.maxY<b.minY||a.minY>b.maxY)};this.boxContainsPoint=function(a,b){return b.x>=a.minX&&b.x<=a.maxX&&b.y>=a.minY&&b.y<=a.maxY};this.expandBox=function(a,b){a.minX=Math.min(a.minX,b.minX);a.minY=Math.min(a.minY,b.minY);a.maxX=Math.max(a.maxX,b.maxX);a.maxY=Math.max(a.maxY,b.maxY)};this.clampBoxToBox=function(a,b){a.minX=Math.max(a.minX,
b.minX);a.minY=Math.max(a.minY,b.minY);a.maxX=Math.min(a.maxX,b.maxX);a.maxY=Math.min(a.maxY,b.maxY)};this.postObject=function(a,b,c,d){b={data:JSON.stringify(b)};d&&jQuery.extend(b,d);$.ajax({type:"POST",url:a,data:b,complete:c,dataType:"json"})};this.setGlobalLoadingCallback=function(a){b.setGlobalCallback(a)};this.setMainLoopCallback=function(a,b,c){for(var b=b||"_wade_default",d=0;d<k.length&&k[d].name!=b;d++);k[d]={func:a,name:b,priority:c||0};k.sort(function(a,b){return b.priority-a.priority})};
this.setLoadingImages=function(a){for(var b=0;b<g.length;b++)document.body.removeChild(g[b]);g.length=0;jQuery.isArray(a)||(a=[a]);for(b=0;b<a.length;b++){var c=document.createElement("img");c.className="loadingImage_class";c.style.display="none";var d=document.getElementById("container");document.body.insertBefore(c,d);c.src=this.getFullPathAndFileName(a[b]);g.push(c)}};this.worldPositionToScreen=function(b,c){return a.renderer.worldPositionToScreen(b,c)};this.worldDirectionToScreen=function(b,c){return a.renderer.worldDirectionToScreen(b,
c)};this.worldBoxToScreen=function(b,c){return a.renderer.worldBoxToScreen(b,c)};this.screenPositionToWorld=function(b,c){return a.renderer.screenPositionToWorld(b,c)};this.screenDirectionToWorld=function(b,c){return a.renderer.screenDirectionToWorld(b,c)};this.screenBoxToWorld=function(b,c){return a.renderer.screenBoxToWorld(b,c)};this.setMinimumInputEventInterval=function(a,b){d.setMinimumIntervalBetweenEvents(a,b)};this.isMouseDown=function(){return d.isMouseDown()};this.unpackSpriteSheet=function(a,
b,c,d,e){for(var c=c||1,d=d||1,f=this.getImage(a),g=f.width/c,f=f.height/d,h=0;h<b.length&&h<c*d;h++){var i=document.createElement("canvas");i.width=g;i.height=f;(new Animation(a,c,d,1,!1,h,h)).draw(i.getContext("2d"),{x:g/2,y:f/2},{x:g,y:f});wade.setImage(b[h],i)}e&&this.unloadImage(a)};this.storeLocalObject=function(a,b){localStorage.setItem(a,JSON.stringify(b))};this.retrieveLocalObject=function(a){return(a=localStorage.getItem(a))&&JSON.parse(a)};this.enableDoubleBuffering=function(b){"undefined"==
typeof b&&(b=!0);p!=b&&(a.renderer.enableDoubleBuffering(b),p=b)};this.isDoubleBufferingEnabled=function(){return p};this.setFullScreen=function(a){var b=document.documentElement;(a=a||"undefined"==typeof a?b.requestFullScreen||b.requestFullscreen||b.mozRequestFullScreen||b.mozRequestFullscreen||b.webkitRequestFullScreen||b.webkitRequestFullscreen||b.msRequestFullScreen||b.msRequestFullscreen:b.cancelFullScreen||b.cancelFullscreen||b.mozCancelFullScreen||b.mozCancelFullscreen||b.webkitCancelFullScreen||
b.webkitCancelFullscreen||b.msCancelFullScreen||b.msCancelFullscreen)&&a.call(b)};this.setLayerSmoothing=function(b,c){"undefined"==typeof c&&(c=!0);a.renderer.setLayerSmoothing(b,c)};this.getLayerSmoothing=function(b){return a.renderer.getLayerSmoothing(b)};this.setSmoothing=function(b){"undefined"==typeof b&&(b=!0);a.renderer.setSmoothing(b)};this.getSmoothing=function(){return a.renderer.getSmoothing()};this.setClickTolerance=function(a){d.setClickTolerance(a)};this.getMousePosition=function(){return d.getMousePosition()};
this.isWebAudioSupported=function(){return!!b.getWebAudioContext()};this.forceOrientation=function(b){if(r!=b){switch(b){case "landscape":r="landscape";break;case "portrait":r="portrait";break;default:r="none"}a.setSimulationDirtyState();a.draw()}};this.getForcedOrientation=function(){return r};this.isScreenRotated=function(){return a.renderer.isScreenRotated()};this.moveCamera=function(a,b){"object"!=typeof a||"number"!=typeof a.x||"number"!=typeof a.y||"number"!=typeof a.z?console.log("Warning - invalid destination for wade.moveCamera(). It needs to be an object with x, y, and z fields."):
"number"!=typeof b&&"function"!=typeof b?console.log("Warning - invalid speed for wade.moveCamera(). It needs to be a number, or a function that returns a number."):this.setMainLoopCallback(function(){var c=wade.getCameraPosition(),d=a.x-c.x,e=a.y-c.y,f=a.z-c.z,g=Math.sqrt(d*d+e*e+f*f),h="number"==typeof b?b:b(g)||0;g<=h*wade.c_timeStep?(wade.setCameraPosition(a),wade.setMainLoopCallback(0,"_wade_camera"),wade.app.onCameraMoveComplete&&wade.app.onCameraMoveComplete()):wade.setCameraPosition({x:c.x+
d*h*wade.c_timeStep/g,y:c.y+e*h*wade.c_timeStep/g,z:c.z+f*h*wade.c_timeStep/g})},"_wade_camera")};this.setCameraTarget=function(a,b,c){a?(b=b||0,c=c||{x:0,y:0},this.setMainLoopCallback(function(){if(a.isInScene()){var d=a.getPosition(),e=wade.getCameraPosition();d.x+=c.x;d.y+=c.y;d.z=e.z;if(b){var e={x:d.x*(1-b)+e.x*b,y:d.y*(1-b)+e.y*b,z:d.z*(1-b)+e.z*b},f=e.x-d.x,g=e.y-d.y,h=e.z-d.z;f*f+g*g+h*h>b*b&&(d=e)}wade.setCameraPosition(d)}},"_wade_cameraTarget")):this.setMainLoopCallback(0,"_wade_cameraTarget")};
this.getAudio=function(a){a=this.getFullPathAndFileName(a);return b.getAudio(a)};this.playSilentSound=function(){var a=b.getWebAudioContext();if(a){var c=a.createOscillator();c.frequency.value=440;var d=a.createGainNode();d.gain.value=0;c.connect(d);d.connect(a.destination);c.start?c.start(0):c.noteOn(0);c.stop?c.stop(0.001):c.noteOff(0.001)}else{a=new Audio;a.src="data:audio/wav;base64,UklGRjoAAABXQVZFZm10IBAAAAABAAEA6AcAANAPAAACABAAZGF0YQYAAAAAAAAAAAA%3D";try{a.play()}catch(e){}}};this.event_mainLoopCallback_=
function(){var a=this;return function(){a.event_mainLoop()}};this.event_mainLoop=function(){var c;e=requestAnimationFrame(this.event_mainLoopCallback_());if(b.isFinishedLoading()){for(c=0;c<g.length;c++)"none"!=g[c].style.display&&(g[c].style.display="none");c=(new Date).getTime();var d=0;m?(d=Math.floor((c-m)/(1E3*wade.c_timeStep)),d=Math.min(2,d)):m=c;d&&(m+=d*wade.c_timeStep,c-m>=wade.c_timeStep&&(m=c));if(h){a.draw();for(c=0;c<d;c++){a.step();for(var f=0;f<k.length;f++){var i=k[f].func;i&&i()}}}else l&&
this.initializeApp()}else for(c=0;c<g.length;c++)g[c].src&&(g[c].style.display="inline")};this.event_appTimerEvent=function(){f=setTimeout("wade.event_appTimerEvent();",1E3*i);a.appTimerEvent()};this.getLayer=function(b){return a.renderer.getLayer(b)};this.updateMouseInOut=function(b,c){a.updateMouseInOut(b,c)};window.console||(window.console={});window.console.log||(window.console.log=function(){})}wade=new Wade;
function Wade_drawFunctions(){this.gradientFill_=function(a,b){return function(c){if(this._visible){if((!this._gradient||this._gradient.colors!=b||this._gradient.direction!=a||this._gradient.size.x!=this._size.x||this._gradient.size.y!=this._size.y||this._gradient.position.x!=this._position.x||this._gradient.position.y!=this._position.y)&&2<=b.length){this._gradient={colors:b,direction:a,size:{x:this._size.x,y:this._size.y},position:{x:this._position.x,y:this._position.y}};this._gradient.gradient=
c.createLinearGradient((this._position.x-this._size.x/2)*a.x,(this._position.y-this._size.y/2)*a.y,(this._position.x+this._size.x/2)*a.x,(this._position.y+this._size.y/2)*a.y);for(var d=0;d<b.length;d++)this._gradient.gradient.addColorStop(d/(b.length-1),b[d])}this._gradient||this._gradient.gradient?(c.save(),c.fillStyle=this._gradient.gradient,c.fillRect(this._position.x-this._size.x/2,this._position.y-this._size.y/2,this._size.x,this._size.y),c.restore()):console.log("Warning: attemptig to draw a sprite with an invalid linear gradient")}}};
this.solidFill_=function(a){return function(b){if(this._visible){var c=b.fillStyle;b.fillStyle=a;b.fillRect(this._position.x-this._size.x/2,this._position.y-this._size.y/2,this._size.x,this._size.y);b.fillStyle=c}}};this.solidFillInt_=function(a){return function(b){if(this._visible){var c=b.fillStyle;b.fillStyle=a;b.fillRect(Math.floor(this._position.x-this._size.x/2),Math.floor(this._position.y-this._size.y/2),Math.floor(this._size.x),Math.floor(this._size.y));b.fillStyle=c}}};this.drawRect_=function(a,
b){return function(c){if(this._visible){var d=c.fillStyle,e=c.lineWidth;c.strokeStyle=a;c.lineWidth=b;c.strokeRect(this._position.x-this._size.x/2+b,this._position.y-this._size.y/2+b,this._size.x-2*b,this._size.y-2*b);c.fillStyle=d;c.lineWidth=e}}};this.radialGradientCircle_=function(a){return function(b){if(this._visible){var c=Math.min(this._size.x,this._size.y)/2;if(!this._gradient||this._gradient.colors!=a||this._gradient.minRadius!=c||this._gradient.position.x!=this._position.x||this._gradient.position.y!=
this._position.y){this._gradient={colors:a,minRadius:c,position:{x:this._position.x,y:this._position.y}};this._gradient.gradient=b.createRadialGradient(this._position.x,this._position.y,0,this._position.x,this._position.y,c);for(c=0;c<a.length;c++)this._gradient.gradient.addColorStop(c/a.length,a[c]);this._gradient.gradient.addColorStop(1,"rgba(0, 0, 0, 0)")}b.save();b.fillStyle=this._gradient.gradient;b.fillRect(this._position.x-this._size.x/2,this._position.y-this._size.y/2,this._size.x,this._size.y);
b.restore()}}};this.solidFade_=function(a,b,c,d,e,f,h,l,j,i){var g=0;return function(k){if(this._visible){if(!this._animations.__fade){var m=new Animation("",1,1,1,!0);this.addAnimation("__fade",m)}this.playAnimation("__fade");var m=k.fillStyle,p=g/j;k.fillStyle="rgba("+Math.floor(a*(1-p)+e*p)+","+Math.floor(b*(1-p)+f*p)+","+Math.floor(c*(1-p)+h*p)+","+(d*(1-p)+l*p)+")";k.fillRect(this._position.x-this._size.x/2,this._position.y-this._size.y/2,this._size.x,this._size.y);k.fillStyle=m;g<j&&(g++,g==
j&&i&&i())}}};this.grid_=function(a,b,c,d){return function(e){e.save();e.lineWidth=d;e.strokeStyle=c;e.lineJoin="round";e.lineCap="round";for(var f=this._size.x/a,h=this._size.y/b,l=this._position.x-this._size.x/2,j=this._position.y-this._size.y/2,i=this._position.x+this._size.x/2,g=this._position.y+this._size.y/2,k=l,m=j,p=0;p<=b;p++)e.beginPath(),e.moveTo(l,m),e.lineTo(i,m),e.stroke(),m+=h;for(h=0;h<=a;h++)e.beginPath(),e.moveTo(k,j),e.lineTo(k,g),e.stroke(),k+=f;e.restore()}};this.alpha_=function(a,
b){return function(c){if(this._visible){var d=c.globalAlpha;c.globalAlpha=a;b.call(this,c);c.globalAlpha=d}}};this.blink_=function(a,b,c){var d=1,e=a;return function(f){if(this._visible){if(0>(e-=wade.c_timeStep))e=d?b:a,d=!d;d&&c.call(this,f);this.setDirtyArea()}}};this.fadeOpacity_=function(a,b,c,d,e){var f=(b-a)*wade.c_timeStep/c,h=a,d=d||Sprite.prototype.draw;return function(c){if(this._visible){var j=h;h=Math[b>a?"min":"max"](b,h+f);var i=c.globalAlpha;c.globalAlpha=h;d.call(this,c);c.globalAlpha=
i;h==b&&1==h?this.setDrawFunction(d):h!=j&&this.setDirtyArea();h==b&&e&&e()}}};this.resizeOverTime_=function(a,b,c,d,e,f,h){var l=(c-a)*wade.c_timeStep/e,j=a,i=(d-b)*wade.c_timeStep/e,g=b,f=f||Sprite.prototype.draw;return function(e){this._visible&&(j=Math[c>a?"min":"max"](c,j+l),g=Math[d>b?"min":"max"](d,g+i),this.setSize(j,g),f.call(this,e),j==c&&g==d&&(this.setDrawFunction(f),h&&h()))}};this.resizePeriodically_=function(a,b,c,d,e,f){var h=1,l=(c-a)*wade.c_timeStep/e,j=a,i=(d-b)*wade.c_timeStep/
e,g=b,f=f||Sprite.prototype.draw;return function(e){if(this._visible){var m=1==h?c:a,p=1==h?b:d,n=1==h?d:b;j=Math[m>(1==h?a:c)?"min":"max"](m,j+l*h);g=Math[n>p?"min":"max"](n,g+i*h);this.setSize(j,g);f.call(this,e);j==m&&g==n&&(h*=-1)}}};this.mirror_=function(a){a=a||Sprite.prototype.draw;return function(b){b.scale(-1,1);var c=this._position.x,d=this._cornerX;this._position.x*=-1;this._cornerX=this._position.x-this._size.x/2;a.call(this,b);this._position.x=c;this._cornerX=d;b.scale(-1,1)}};this.flip_=
function(a){return function(b){b.scale(1,-1);var c=this._position.y,d=this._cornerY;this._position.y*=-1;this._cornerY=this._position.y-this._size.y/2;a.call(this,b);this._position.y=c;this._cornerY=d;b.scale(1,-1)}}}wade.drawFunctions=new Wade_drawFunctions;
